classdef ConvertUTCTimeTests < matlab.unittest.TestCase
    methods (Test)
        function TestVallado(testCase) 
            % Vallado example 3-7
            utc_time = datetime(2004, 5, 14, 10, 43, 0, "TimeZone", "America/Denver");
            utc_time.TimeZone = 'UTC';
            utc_time.TimeZone = '';

            ut1_utc_sec = -0.463326;

            converted_time = ConvertUTCTime(...
                utc_time, ...
                ut1_utc_sec);

            expected_utc_time = utc_time;
            expected_ut1_time = datetime(2004, 5, 14, 16, 42, 59.5367);
            expected_tai_time = datetime(2004, 5, 14, 16, 43, 32.0000);
            expected_gps_time = datetime(2004, 5, 14, 16, 43, 13.0000);
            expected_tt_time  = datetime(2004, 5, 14, 16, 44, 04.1840);
            expected_tdb_time = datetime(2004, 5, 14, 16, 44, 04.18523820776575);

            testCase.verifyEqual( ...
                seconds(converted_time.utc - expected_utc_time), ...
                0.0, ...
                'AbsTol', 1e-4); 
            testCase.verifyEqual( ...
                seconds(converted_time.ut1 - expected_ut1_time), ...
                0.0, ...
                'AbsTol', 1e-4); 
            testCase.verifyEqual( ...
                seconds(converted_time.tai - expected_tai_time), ...
                0.0, ...
                'AbsTol', 1e-4); 
            testCase.verifyEqual( ...
                seconds(converted_time.gps - expected_gps_time), ...
                0.0, ...
                'AbsTol', 1e-4); 
            testCase.verifyEqual( ...
                seconds(converted_time.tt - expected_tt_time), ...
                0.0, ...
                'AbsTol', 1e-4); 
            testCase.verifyEqual( ...
                seconds(converted_time.tdb - expected_tdb_time), ...
                0.0, ...
                'AbsTol', 1e-6); 
        end
    end
end