classdef SimpleDragGCRFTests < matlab.unittest.TestCase
    methods (Test)
        function TestSingleVector(testCase)

            position_gcrf = transpose([ ...
                100, 0, 0; ...
            ]);
            velocity_gcrf = transpose([ ...
                10, 0, 0; ...
            ]);
            coefficient_of_drag       = 2;
            effective_area            = 1;
            mass                      = 3;
            reference_air_density     = 4;
            reference_radial_distance = 90;
            decay_rate                = 9;
            earth_rotation_rate       = 7e-5;

            [drag_gcrf] = SimpleDragGCRF(...
                position_gcrf, ...
                velocity_gcrf, ...
                coefficient_of_drag, ...
                effective_area, ...
                mass, ...
                reference_air_density, ...
                reference_radial_distance, ...
                decay_rate, ...
                earth_rotation_rate);

            expected_drag_gcrf = [
                 -43.8924091280237;
                0.0307246863896166;
                                 0;
            ];

            testCase.verifyEqual( ...
                drag_gcrf, ...
                expected_drag_gcrf, ...
                'AbsTol', 1e-9); 
        end

        function TestMultipleVector(testCase)

            position_gcrf = transpose([ ...
                100, 0, 0;
                100, 100, 0;
            ]);
            velocity_gcrf = transpose([ ...
                10, 0, 0;
                20, 20, 20;
            ]);
            coefficient_of_drag       = [2; 2.1];
            effective_area            = 1;
            mass                      = 3;
            reference_air_density     = 4;
            reference_radial_distance = 90;
            decay_rate                = 9;
            earth_rotation_rate       = 7e-5;

            [drag_gcrf] = SimpleDragGCRF(...
                position_gcrf, ...
                velocity_gcrf, ...
                coefficient_of_drag, ...
                effective_area, ...
                mass, ...
                reference_air_density, ...
                reference_radial_distance, ...
                decay_rate, ...
                earth_rotation_rate);

            expected_drag_gcrf = transpose([
                 -43.8924091280237, 0.0307246863896166, 0;
                 -3.20306729787058, -3.20082593523899, -3.20194661655479;
            ]);

            testCase.verifyEqual( ...
                drag_gcrf, ...
                expected_drag_gcrf, ...
                'AbsTol', 1e-9); 
        end
    end
end