classdef StateVectorFromOrbitalElementsTests < matlab.unittest.TestCase
    methods (Test)
        function test1(testCase)
            % From Vallado's textbook
            semiparameter               = 11067.790 .* Units.kilometers;
            eccentricity                = 0.83285;
            inclination                 = 87.87 .* Units.degrees;
            longitude_of_ascending_node = 227.89 .* Units.degrees;
            argument_of_periapsis       = 53.38 .* Units.degrees;
            true_anomaly                = 92.335 .* Units.degrees;
            argument_of_latitude        = 0;
            true_longitude              = 0;
            true_argument_of_periapsis  = 0;

            gravitational_parameter = 398600 .* (Units.kilometers).^3 ./ (Units.seconds).^2;
        
            expected_position_eci = [6525.368; 6861.532; 6449.119] .* Units.kilometers;
            expected_velocity_eci = [4.902279; 5.533140; -1.975710] .* Units.kilometers ./ Units.seconds;

            [...
                position_eci, ...
                velocity_eci] = ...
            StateVectorFromOrbitalElements( ...
                semiparameter, ...
                eccentricity, ...
                inclination, ...
                longitude_of_ascending_node, ...
                argument_of_periapsis, ...
                true_anomaly, ...
                argument_of_latitude, ...
                true_longitude, ...
                true_argument_of_periapsis, ...
                gravitational_parameter);

            testCase.verifyEqual( ...
                position_eci, ...
                expected_position_eci, ...
                'RelTol', 1e-4);
            testCase.verifyEqual( ...
                velocity_eci, ...
                expected_velocity_eci, ...
                'RelTol', 1e-4);
        end
    end
end