function [julian_date, modified_julian_date] = JulianDate( ...
        year, ...
        month, ...
        day, ...
        hour, ...
        minute, ...
        second) 
    % Computes the Julian date and modified Julian date.
    %
    % Note, this function only works between 1900 and 2100.
    % 
    % Requires:
    % Returns:
    % References:
    % 
    assert(year > 1900 && year < 2100, "Function domain only defined between 1900 and 2100.");

    % Vallado, Algorithm 14
    julian_date = 367 * year ...
        - floor((7 * (year + floor((month + 9) / 12))) / 4) ...
        + floor((275 * month) / 9) ...
        + day ...
        + 1721013.5 + ...
        (3600 * hour + 60 * minute + second) / 86400;

    modified_julian_date = julian_date - 2400000.5;
end