classdef ComputeNutation1980Tests < matlab.unittest.TestCase
    methods (Test)
        function TestValladoExample(testCase)
            % Vallado, Fundamentals of Astrodynamics and Applications, 5th edition
            % Example 3-15

            % julian_date_tt = 2453101.828154745;
            % julian_centuries_since_epoch = TerrestrialTimeJulianCenturiesSinceJ2000(julian_date_tt);
            julian_centuries_since_epoch = 0.0426236319;

            longitude_earth_orientation_parameter_deg = -0.052195 * Conversions.ARCSECONDS_TO_DEGREES;
            obliquity_earth_orientation_parameter_deg = -0.003875 * Conversions.ARCSECONDS_TO_DEGREES;

            [ ...
                moon_mean_anomaly_deg, ...
                sun_mean_anomaly_deg, ...
                moon_mean_argument_of_latitude_deg, ...
                sun_mean_elongation_deg, ...
                moon_mean_longitude_of_the_ascending_node_deg] = ...
            ComputeDelaunayNutationParameters1980( ...
                julian_centuries_since_epoch);

            [...
                mean_obliquity_of_ecliptic_1980_deg] = ...
            ComputeMeanObliquityOfTheEcliptic1980( ...
                julian_centuries_since_epoch);

            [ ...
                nutation_in_longitude_1980_deg, ...
                nutation_in_obliquity_1980_deg, ...
                true_obliquity_1980_deg] = ...
            ComputeNutationParameters1980(...
                julian_centuries_since_epoch, ...
                moon_mean_anomaly_deg, ...
                sun_mean_anomaly_deg, ...
                moon_mean_argument_of_latitude_deg, ...
                sun_mean_elongation_deg, ...
                moon_mean_longitude_of_the_ascending_node_deg, ...
                mean_obliquity_of_ecliptic_1980_deg, ...
                longitude_earth_orientation_parameter_deg, ...
                obliquity_earth_orientation_parameter_deg);

            expected_nutation_in_longitude_1980_deg = wrapTo360(-0.0034108);
            expected_nutation_in_obliquity_1980_deg = wrapTo360(0.0020316);
            expected_true_obliquity_1980_deg        = wrapTo360(23.4407685);

            testCase.verifyEqual( ...
                nutation_in_longitude_1980_deg, ...
                expected_nutation_in_longitude_1980_deg, ...
                'AbsTol', 1e-9); 

            testCase.verifyEqual( ...
                nutation_in_obliquity_1980_deg, ...
                expected_nutation_in_obliquity_1980_deg, ...
                'AbsTol', 1e-9); 

            testCase.verifyEqual( ...
                true_obliquity_1980_deg, ...
                expected_true_obliquity_1980_deg, ...
                'AbsTol', 1e-9); 
        end
    end
end