classdef EGM96GravitationalAccelerationTests < matlab.unittest.TestCase
    methods (Test)
        function TestAgainstBuiltIn(testCase)   
                
            earth_gravitational_parameter = 3986004.415E+8;
            earth_radius                  = 6378136.3;

            position_itrf = transpose([
                earth_radius + 100e3, 0, 0; 
                earth_radius/sqrt(2) + 100e3, earth_radius/sqrt(2), 0; 
                earth_radius/sqrt(2) + 100e3, earth_radius/sqrt(2), 500e3; 
            ]);

            % Get the path to the model.
            current_file_path = matlab.desktop.editor.getActiveFilename;
            [current_folder, ~, ~] = fileparts(current_file_path);
            model_path = fullfile(current_folder, "EGM96_20.mat");

            % Invoke the builtin spherical harmonic model
            degree = 20;
            [gx, gy, gz] = gravitysphericalharmonic(...
                transpose(position_itrf), ...
                'Custom', ...
                degree, ...
                {model_path, @load}, ...
                "Warning");

            expected_gravitational_acceleration_itrf = transpose([gx, gy, gz]);
            
            [gravitational_acceleration_itrf] = ...
                EGM96GravitationalAcceleration(...
                    position_itrf, ...
                    earth_gravitational_parameter, ...
                    earth_radius, ...
                    degree);

            testCase.verifyEqual( ...
                gravitational_acceleration_itrf, ...
                expected_gravitational_acceleration_itrf, ...
                'AbsTol', 1e-9);  
        end
    end
end